openapi: 3.0.1
info:
  title: zulia-ui-rest-service
  version: 1.0.0
paths:
  /:
    get:
      operationId: home
      responses:
        "200":
          description: home 200 response
          content:
            text/plain:
              schema:
                type: string
  /create-user:
    post:
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserEntity"
        required: true
      responses:
        "200":
          description: createUser 200 response
  /forbidden-test:
    get:
      operationId: forbiddenTest
      responses:
        "200":
          description: forbiddenTest 200 response
          content:
            text/plain:
              schema:
                type: string
  /home-test:
    get:
      operationId: homeTest
      responses:
        "200":
          description: homeTest 200 response
          content:
            text/plain:
              schema:
                type: string
  /home-test-admin:
    get:
      operationId: homeTestAdmin
      responses:
        "200":
          description: homeTestAdmin 200 response
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    UserEntity:
      required:
      - dateCreated
      - hashedPassword
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        hashedPassword:
          type: string
        dateCreated:
          type: string
          format: date-time
        roles:
          type: array
          nullable: true
          items:
            type: string
